import { mkdir, writeFile } from 'node:fs/promises';
import pino from 'pino';
import { loadConfig } from '../src/config/load-config.js';
import { loadEnv, resolveSolanaRpcUrl } from '../src/config/env.js';
import { createConnection } from '../src/solana/connection.js';
import { getTokenInfo } from '../src/solana/token-info.js';
import { getWalletSnapshots } from '../src/wallet/balances.js';
import { getJupiterMarketSnapshot } from '../src/market-data/jupiter-market.js';

const env = loadEnv();
const logger = pino({ level: env.LOG_LEVEL });
const configPath = process.argv.slice(2).find((arg) => arg !== '--') ?? 'config/market-maker.example.json';
const config = loadConfig(configPath);
const connection = createConnection(env);
const rpc = resolveSolanaRpcUrl(env);

logger.info({ rpcProvider: rpc.provider, rpcConfigured: rpc.configured, tokenMint: config.tokenMint }, 'starting read-only observation');

const tokenInfo = await getTokenInfo(connection, config.tokenMint);
const wallets = await getWalletSnapshots({ connection, wallets: config.wallets, tokenMint: config.tokenMint });
const market = await getJupiterMarketSnapshot({
  tokenMint: config.tokenMint,
  tokenDecimals: tokenInfo.decimals,
  quoteMint: config.quoteMint,
  quoteDecimals: 9,
  quoteSizeSol: Math.min(config.globalRisk.maxTradeSol, 0.01),
  slippageBps: config.globalRisk.maxSlippageBps,
  quoteUrl: env.JUPITER_QUOTE_URL,
  apiKey: env.JUPITER_API_KEY
});

const status = {
  mode: config.mode,
  health: 'warning' as const,
  cluster: config.cluster,
  venue: 'jupiter-read-only',
  lastObservationAt: market.observedAt,
  liveTradingEnabled: false as const,
  wallet: {
    name: wallets[0]?.name ?? config.wallets[0]?.name ?? 'unknown-wallet',
    pubkey: wallets[0]?.pubkey ?? config.wallets[0]?.pubkey ?? 'unknown-public-key',
    solBalance: wallets[0]?.solBalance ?? null,
    tokenBalance: wallets[0]?.tokenBalance ?? null
  },
  token: {
    mint: tokenInfo.mint,
    symbol: tokenInfo.mint === 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' ? 'USDC' : 'TOKEN',
    decimals: tokenInfo.decimals,
    supplyUi: tokenInfo.supplyUi
  },
  quote: {
    mint: config.quoteMint,
    symbol: config.quoteMint === 'So11111111111111111111111111111111111111112' ? 'SOL' : 'QUOTE',
    decimals: 9
  },
  market: {
    referencePrice: market.referencePrice,
    estimatedSlippageBps: market.estimatedSlippageBps,
    volatilityBps: market.volatilityBps
  },
  risk: config.globalRisk,
  notes: [
    'Generated by scripts/observe.ts from public read-only data.',
    'No private keys, signing, swaps, or transactions were used.',
    'Live trading remains disabled.'
  ],
  source: 'status-file' as const
};

await mkdir('runtime', { recursive: true });
await writeFile('runtime/market-maker-status.local.json', `${JSON.stringify(status, null, 2)}\n`);

logger.info({ tokenInfo, wallets, market, statusFile: 'runtime/market-maker-status.local.json' }, 'read-only observation complete');
